### ISSUE TITLE
ftbfs: tryuwtmpx.c: new errors

### ISSUE THREAD

**Issue by powerman** [clan/runit#1]
There are no errors in master branch, but in ftbfs branch commit a9089b1 I get 2 new errors:

```
tryuwtmpx.c:7:14: error: invalid use of undefined type ‘struct futmpx’
tryuwtmpx.c:4:15: error: storage size of ‘ut’ isn’t known
```

gcc (Gentoo Hardened 13.3.1_p20240614 p17) 13.3.1 20240614

**Comment by powerman** [comment]
Same errors with gcc (Gentoo Hardened 14.2.1_p20240817 p4) 14.2.1 20240817.

**Comment by powerman** [comment]
Same errors with gcc (Gentoo Hardened 15.0.0_pre20240818-r1 p10) 15.0.0 20240818 (experimental).

**Comment by clan** [comment]
this one is not a build error, it's part of a feature test to determine the contents of uw_tmp.h

see https://github.com/clan/runit/blob/master/admin/runit-2.1.2/src/Makefile#L101

This is also the reason why my first patch remove some redirection >/dev/null, then I can check the error is desired or not.

**Comment by powerman** [comment]
I see. At a glance it makes sense, but in practice - how exactly you're doing to manage this?

I mean, let's pretend some user gets error not because of unknown types, but because of newer GCC. As these errors are ignored and handled by finally disable the feature user may not even notice this (switching to fallback or disabling the feature) for a long time.

If you wanna control this I think it's not enough to just output errors, you need to improve fallback logic by ignoring only specific errors (like "unknown type") but not all errors - any error which is not in a list of known-expected errors should fail the build instead of switching to fallback. Without this it's probably better to hide errors as original code does to avoid useless questions like mine in this issue.

**Comment by clan** [comment]
I think this kind of output information is for developer only, the end-user don't care about this.
For Gentoo Linux, people will post the detailed build information if they found somethings wrong, rather than what we faced now: important information were silently discarded, I had to read Makefile etc. to find the real reason.

>because of newer GCC

In case of runit, the test should provide a fallback solution which *must* work, but not as expected. In general, most of softwares use autoconf/... to get build time config, but runit don't use it for simplicity.

I'll try to find a better solution later. For now, let's solve the found problem(s) first,
